App\Domain\Page\Entity\Page:
  table: 'page'
  type: entity
  fields:
    id:
      id: true
      type: uuid
    name:
      type: string
      unique: true
    icon:
      type: string
    alias:
      type: string
    config:
      type: json
    groupId:
      type: integer
      name: group_id
    createdAt:
      type: datetime_immutable
      name: created_at
    updatedAt:
      type: datetime_immutable
      name: updated_at
      nullable: true