services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Application\Consumer\:
    resource: '%kernel.project_dir%/src/Application/Consumer/**/*Consumer.php'
    arguments:
      $logger: '@monolog.logger.rabbit_consumers'