imports:
  - { resource: 'http.yaml' }
  - { resource: 'cli.yaml' }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Application\Cli\Handler\:
    resource: '%kernel.project_dir%/src/Application/Cli/Handler/*Handler.php'

  App\Application\Service\:
    resource: '%kernel.project_dir%/src/Application/Service/**/*Service.php'
    autowire: true