imports:
  - { resource: 'http.yaml' }
  - { resource: 'cli.yaml' }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Application\Service\Validation\Sensor\SensorValidationService: ~

  App\Application\Service\Validation\Relay\RelayValidationService: ~

  App\Application\Service\Validation\Security\SecurityValidationService: ~

  App\Application\Service\Validation\FireSecurity\FireSecurityValidationService: ~

  App\Application\Cli\Handler\TelegramNotificationHandler: ~

  App\Application\Service\DeviceData\DataValidationService: ~

  App\Application\Service\Alert\AlertService: ~

  App\Application\Service\DeviceData\DataResolver: ~

  App\Application\Service\DeviceData\DataCacheService: ~

  App\Application\Service\DeviceData\DeviceCacheService: ~