imports:
  - { resource: 'http.yaml' }
  - { resource: 'cli.yaml' }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Application\Service\SignUpService:
    arguments:
      $email: '%env(EMAIL_REGISTRATION_EMAIL)%'
      $subject: '%env(EMAIL_REGISTRATION_EMAIL_SUBJECT)%'