imports:
  - { resource: 'http.yaml' }
  - { resource: 'cli.yaml' }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Application\Service\Validation\Sensor\SensorValidationService: ~

  App\Application\Service\Validation\Relay\RelayValidationService: ~