framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_DSN)%'
        pools:
            doctrine.result_cache_pool:
                adapter: app.cache.adapter.redis