doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'
    enable_profiler: '%kernel.debug%'

    transactional: true
    check_database_platform: true
    all_or_nothing: false
    organize_migrations: false

    storage:
      table_storage:
        table_name: 'doctrine_migration_versions'