doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'
    storage:
        table_storage:
            table_name: 'doctrine_migration_versions'

doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
            datetime_immutable: App\Infrastructure\Doctrine\Type\DatetimeImmutable
            time_immutable: App\Infrastructure\Doctrine\Type\TimeImmutable
            datetime_immutable_microseconds: App\Infrastructure\Doctrine\Type\DateTimeImmutableMicroType
            datetime_microseconds: App\Infrastructure\Doctrine\Type\DateTimeMicroType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            user:
                type: yml
                prefix: 'App\Domain\Doctrine\Identity\Entity'
                dir: '%kernel.project_dir%/config/mappings/Identity'
            embedded:
                type: yml
                prefix: 'App\Domain\Doctrine\Common\Embedded'
                dir: '%kernel.project_dir%/config/mappings/Embedded'
            sensor:
                type: yml
                prefix: 'App\Domain\Doctrine\Sensor\Entity'
                dir: '%kernel.project_dir%/config/mappings/Sensor'
            relay:
                type: yml
                prefix: 'App\Domain\Doctrine\Relay\Entity'
                dir: '%kernel.project_dir%/config/mappings/Relay'
            security:
                type: yml
                prefix: 'App\Domain\Doctrine\Security\Entity'
                dir: '%kernel.project_dir%/config/mappings/Security'
            fire-security:
                type: yml
                prefix: 'App\Domain\Doctrine\FireSecurity\Entity'
                dir: '%kernel.project_dir%/config/mappings/FireSecurity'
            site-page:
                type: yml
                prefix: 'App\Domain\Doctrine\Page\Entity'
                dir: '%kernel.project_dir%/config/mappings/Page'
            visual-notify:
                type: yml
                prefix: 'App\Domain\Doctrine\VisualNotification\Entity'
                dir: '%kernel.project_dir%/config/mappings/VisualNotification'