doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
            datetime_immutable: App\Infrastructure\Doctrine\Type\DatetimeImmutable
            time_immutable: App\Infrastructure\Doctrine\Type\TimeImmutable
            datetime_immutable_microseconds: App\Infrastructure\Doctrine\Type\DateTimeImmutableMicroType
            datetime_microseconds: App\Infrastructure\Doctrine\Type\DateTimeMicroType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            sensor:
                type: yml
                prefix: 'App\Domain\Doctrine\Sensor\Entity'
                dir: '%kernel.project_dir%/config/mappings/Sensor'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
