framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    delay: 1000
                    multiplier: 2
                    max_retries: 3
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
            App\Domain\Notification\Entity\TelegramNotificationMessage: async
            App\Domain\Notification\Entity\AliceNotificationMessage: async
            App\Domain\Notification\Entity\DiscordNotificationMessage: async
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
