monolog:
    channels:
        - deprecation
        - mqtt_transport
        - periodic_handler
        - telegram_service
        - event_handler
        - quasar_service
        - discord_service
        - smart_home

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            console:
                type: console
                process_psr_3_messages: false
                channels:
                    - mqtt_transport
                    - periodic_handler
                    - telegram_service
                    - event_handler
                    - quasar_service
                    - discord_service
                verbosity_levels:
                    VERBOSITY_NORMAL: INFO
            mqtt_transport:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%.mqtt_transport.log'
                channels: [ mqtt_transport ]
            periodic_handler:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%.periodic_handler.log'
                channels: [ periodic_handler ]
            telegram_service:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%.telegram_sender_service.log'
                channels: [ telegram_service ]
            event_handler:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%.event_handler.log'
                channels: [ event_handler ]
            quasar_service:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%.quasar_service.log'
                channels: [ quasar_service ]
            discord_service:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%.discord_service.log'
                channels: [ discord_service ]
            smart_home:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%.smart_home.log'
                channels: [ smart_home ]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [ 404, 405 ]
                channels: [ "!event" ]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [ 404, 405 ]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: [ "!event", "!doctrine" ]
            deprecation:
                type: stream
                channels: [ deprecation ]
                path: php://stderr
