when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
        register_error_listener: false
        register_error_handler: false
        tracing:
            enabled: true
        options:
            environment: '%env(SENTRY_ENVIRONMENT)%'
            traces_sample_rate: 1.0
            ignore_exceptions:
                - 'Symfony\Component\ErrorHandler\Error\FatalError'
                - 'Symfony\Component\Debug\Exception\FatalErrorException'

    monolog:
        handlers:
            sentry:
                type: sentry
                level: !php/const Monolog\Logger::ERROR
                hub_id: Sentry\State\HubInterface
                fill_extra_context: true # Enables sending monolog context to Sentry
                process_psr_3_messages: false # Disables the resolution of PSR-3 placeholders
