when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
        register_error_listener: false
        tracing:
            enabled: true
        options:
            environment: '%env(SENTRY_ENVIRONMENT)%'
            traces_sample_rate: 1.0
