sentry:
  dsn: '%env(SENTRY_DSN)%'
  register_error_listener: false
  options:
    environment: '%kernel.environment%'
    send_default_pii: true

monolog:
  handlers:
    sentry:
      type: service
      id: Sentry\Monolog\Handler

services:
  Sentry\Monolog\Handler:
    arguments:
      $hub: '@Sentry\State\HubInterface'
      $level: !php/const Monolog\Logger::ERROR

  Monolog\Processor\PsrLogMessageProcessor:
    tags: { name: monolog.processor, handler: sentry }