twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        notifications: '@App\Application\Service\VisualNotification\VisualNotificationService'

when@test:
    twig:
        strict_variables: true
