twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        notifications: '@App\Domain\VisualNotification\Service\VisualNotificationService'

when@test:
    twig:
        strict_variables: true
