stages:
  - manual-clean
  - preparation
  - testing
  - deploy

variables:
  SSH_COMMAND: $SSH_COMMAND
  DB_HOST: $DB_HOST

compose:
  stage: preparation
  tags:
    - uberserver
  script:
    - docker-compose -f docker-compose.ci.yaml down --remove-orphans
    - cp -n .env.test .env.test.local
    - sed -i 's/uberserver/'"$DB_HOST"'/g' .env.test.local
    - cat .env.test.local
    - docker-compose -f docker-compose.ci.yaml build php-fpm
    - rm .env.test.local -f
    - docker-compose -f docker-compose.ci.yaml up -d
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm php -v
  after_script:
    - >
      if [ $CI_JOB_STATUS == 'success' ]; then
        echo 'Success'
      else
        echo 'Dropping build files'
        docker-compose -f docker-compose.ci.yaml down --remove-orphans
        docker system prune -a -f
      fi

tests:
  stage: testing
  tags:
    - uberserver
  dependencies:
    - compose
  script:
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm chmod 777 -R ./var ./tests/_output ./tests/_support
    - docker-compose -f docker-compose.ci.yaml exec -T cat .env.test.local
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm php bin/console d:d:d --force --env test
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm php bin/console d:d:c --env test
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm php bin/console doctrine:migrations:migrate --env test --no-interaction
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm ./vendor/codeception/codeception/codecept build
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm ./vendor/codeception/codeception/codecept run acceptance --xml --html
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm ./vendor/codeception/codeception/codecept clean
    - docker-compose -f docker-compose.ci.yaml down --remove-orphans
    - docker system prune -a -f
#  artifacts:
#    when: always
#    expire_in: 1 week
#    paths:
#      - tests/_output
#    # make the report available in Gitlab UI. see https://docs.gitlab.com/ee/ci/unit_test_reports.html
#    reports:
#      junit: tests/_output/report.xml
  after_script:
    - >
      if [ $CI_JOB_STATUS == 'success' ]; then
        echo 'Success'
      else
        echo 'Dropping build files'
        docker-compose -f docker-compose.ci.yaml down --remove-orphans
        docker system prune -a -f
      fi

clean:
  stage: manual-clean
  tags:
    - uberserver
  script:
    - docker-compose -f docker-compose.ci.yaml down --remove-orphans
    - docker system prune -a -f
  when: manual

deploy_prod:
  stage: deploy
  tags:
    - uberserver
  script:
    - df -H /
    - |
      ssh -T "$SSH_COMMAND" /bin/bash -s << EOT
      cd uberserver/
      git checkout master
      git fetch --all
      git reset --hard HEAD
      git status
      git pull
      df -H /
      make pull
      docker-compose exec -T php-fpm composer install --no-dev --optimize-autoloader
      docker-compose exec -T php-fpm php bin/console d:m:m --no-interaction
      docker-compose exec -T php-fpm php bin/console cache:clear
      docker-compose exec -T php-fpm chmod 777 -R ./var
      docker-compose exec -T php-fpm php bin/console cache:warmup
      make restart
      make ps
      docker-compose exec -T php-fpm chmod 777 -R ./var/cache
      EOT
  dependencies:
    - tests
  environment:
    name: deploy
  only:
    - master
