stages:
  - manual-clean
  - preparation
  - testing
  - deploy

variables:
  SSH_COMMAND: $SSH_COMMAND
  DB_HOST: $DB_HOST

composer:
  stage: preparation
  tags:
    - uberserver
  script:
    - docker-compose -f docker-compose.ci.yaml down
    - docker-compose -f docker-compose.ci.yaml up -d
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm chmod 777 -R ./
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm rm -rf ./var ./vendor
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm php -v
  after_script:
    - >
      if [ $CI_JOB_STATUS == 'success' ]; then
        echo 'Success'
      else
        echo 'Droping files'
        docker-compose -f docker-compose.ci.yaml run -T php-fpm chmod 777 -R ./
        docker-compose -f docker-compose.ci.yaml run -T php-fpm rm -rf ./var ./vendor .env.test.local
      fi

tests:
  stage: testing
  tags:
    - uberserver
  dependencies:
    - composer
  script:
    - docker-compose -f docker-compose.ci.yaml down --remove-orphans
    - docker-compose -f docker-compose.ci.yaml up -d
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm rm -rf .env.test.local
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm cp -n .env.test .env.test.local
    - sed -i 's/uberserver/'"$DB_HOST"'/g' .env.test.local
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm chmod 777 -R ./
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm php bin/console d:d:d --force --env test
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm php bin/console d:d:c --env test
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm php bin/console doctrine:migrations:migrate --env test --no-interaction
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm ./vendor/codeception/codeception/codecept run
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm ./vendor/codeception/codeception/codecept clean
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm chmod 777 -R ./
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm rm -rf ./var ./vendor
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm rm -rf .env.test.local
    - docker-compose -f docker-compose.ci.yaml down --remove-orphans
  after_script:
    - >
      if [ $CI_JOB_STATUS == 'success' ]; then
        echo 'Success'
      else
        echo 'Droping build files'
        docker-compose -f docker-compose.ci.yaml run -T php-fpm chmod 777 -R ./
        docker-compose -f docker-compose.ci.yaml run -T php-fpm rm -rf ./var ./vendor .env.test.local
        docker-compose -f docker-compose.ci.yaml down --remove-orphans
      fi

clean:
  stage: manual-clean
  tags:
    - uberserver
  script:
    - docker-compose -f docker-compose.ci.yaml down
    - docker-compose -f docker-compose.ci.yaml up -d
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm chmod 777 -R ./
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm rm -rf ./var ./vendor
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm rm -rf .env.test.local
  when: manual

deploy_prod:
  stage: deploy
  tags:
    - uberserver
  script:
    - df -H /
    - |
      ssh -T "$SSH_COMMAND" /bin/bash -s << EOT
      cd uberserver/
      git checkout master
      git fetch --all
      git reset --hard HEAD
      git status
      git pull
      df -H /
      make pull
      docker-compose exec -T php-fpm chown -R root:root ./
      docker-compose exec -T php-fpm composer install --no-dev --optimize-autoloader
      docker-compose exec -T php-fpm chmod 777 -R ./
      docker-compose exec -T php-fpm php bin/console d:m:m --no-interaction
      docker-compose exec -T php-fpm php bin/console cache:clear
      docker-compose exec -T php-fpm chmod 777 -R ./
      make restart
      make ps
      EOT
  dependencies:
    - tests
  environment:
    name: deploy
  only:
    - master
