stages:
  - manual-clean
  - preparation
  - testing
  - deploy

variables:
  SSH_COMMAND: $SSH_COMMAND
  DB_HOST: $DB_HOST

composer:
  stage: preparation
  tags:
    - uberserver
  script:
    - docker-compose -f docker-compose.ci.yaml down
    - docker-compose -f docker-compose.ci.yaml up -d
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm chmod -R 777 ./
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm php -v

tests:
  stage: testing
  tags:
    - uberserver
  dependencies:
    - composer
  script:
    - docker-compose -f docker-compose.ci.yaml down --remove-orphans
    - docker-compose -f docker-compose.ci.yaml up -d
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm rm -rf .env.test.local
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm cp -n .env.test .env.test.local
    - sed -i 's/uberserver/'"$DB_HOST"'/g' .env.test.local
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm chmod -R 777 ./
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm php bin/console d:d:d --force --env test
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm php bin/console d:d:c --env test
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm php bin/console doctrine:migrations:migrate --env test --no-interaction
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm ./vendor/codeception/codeception/codecept run
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm ./vendor/codeception/codeception/codecept clean
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm chmod -R 777 ./
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm rm -rf ./var ./vendor
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm rm -rf .env.test.local

clean:
  stage: manual-clean
  tags:
    - uberserver
  script:
    - docker-compose -f docker-compose.ci.yaml down
    - docker-compose -f docker-compose.ci.yaml up -d
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm chmod -R g+rw ./
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm rm -rf ./var ./vendor
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm rm -rf .env.test.local
  when: manual

deploy_prod:
  stage: deploy
  tags:
    - uberserver
  script:
    - df -H /
    - |
      ssh -T "$SSH_COMMAND" /bin/bash -s << EOT
      cd uberserver/
      git checkout master
      git fetch --all
      git reset --hard HEAD
      git status
      git pull
      df -H /
      make up
      make cache
      docker-compose stop php-fpm
      docker-compose run -T php-fpm composer install --no-dev --optimize-autoloader
      docker-compose run -T php-fpm php bin/console d:m:m --no-interaction
      make restart
      make cache
      make ps
      EOT
  dependencies:
    - tests
  environment:
    name: deploy
  only:
    - master
