stages:
  - manual-clean
  - lint
  - build
  - compose
  - testing
  - deploy

variables:
  SSH_COMMAND: $SSH_COMMAND
  DB_HOST: $DB_HOST

build:
  stage: build
  tags:
    - uberserver
  script:
    - docker-compose -f docker-compose.ci.yaml down --remove-orphans
    - cp -n .env.test .env.test.local
    - sed -i 's/uberserver/'"$DB_HOST"'/g' .env
    - sed -i 's/uberserver/'"$DB_HOST"'/g' .env.test.local
    - docker-compose -f docker-compose.ci.yaml build php-fpm
    - rm .env.test.local -f
    - docker-compose -f docker-compose.ci.yaml up -d
  after_script:
    - >
      if [ $CI_JOB_STATUS == 'success' ]; then
        echo 'Success'
      else
        echo 'Dropping build files'
        docker-compose -f docker-compose.ci.yaml down --remove-orphans
        docker image rm uberserver-symfony_php-fpm
      fi

compose:
  stage: compose
  interruptible: true
  tags:
    - uberserver
  dependencies:
    - build
  script:
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm php -v
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm chmod 777 -R ./var ./tests/_output ./tests/_support

tests:
  stage: testing
  tags:
    - uberserver
  dependencies:
    - compose
  script:
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm php bin/console d:d:d --force
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm php bin/console d:d:c
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm php bin/console doctrine:migrations:migrate --no-interaction
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm ./vendor/codeception/codeception/codecept build
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm ./vendor/codeception/codeception/codecept run
    - docker-compose -f docker-compose.ci.yaml down --remove-orphans
  after_script:
    - >
      if [ $CI_JOB_STATUS == 'success' ]; then
        echo 'Success'
        docker image rm uberserver-symfony_php-fpm
      else
        echo 'Dropping build files'
        docker-compose -f docker-compose.ci.yaml down --remove-orphans
        docker image rm uberserver-symfony_php-fpm
      fi

clean:
  stage: manual-clean
  tags:
    - uberserver
  script:
    - docker-compose -f docker-compose.ci.yaml down --remove-orphans
    - docker system prune -a -f
  when: manual

psalm:
  stage: lint
  script:
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm php /var/www/vendor/bin/psalm --no-cache --output-format=phpstorm
  when: manual

deploy_prod:
  stage: deploy
  tags:
    - uberserver
  script:
    - df -H /
    - |
      ssh -T "$SSH_COMMAND" /bin/bash -s << EOT
      cd uberserver/
      git checkout master
      git fetch --all
      git reset --hard HEAD
      git status
      git pull
      df -H /
      make pull
      make down
      docker-compose run -T commands composer install --no-dev --optimize-autoloader
      docker-compose run -T commands php bin/console d:m:m --no-interaction 
      docker-compose run -T commands chmod 777 -R ./var
      docker-compose run -T commands php bin/console cache:clear
      docker-compose run -T commands php bin/console cache:warmup
      docker-compose run -T commands chmod 777 -R ./var/cache
      make restart
      make ps
      EOT
  dependencies:
    - tests
  environment:
    name: deploy
  only:
    - master
