default:
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - vendor/

stages:
#  - lint
  - testing
  - deploy

variables:
  ALERT_HOST: $ALERT_HOST

test-build:
  stage: testing
  tags:
    - smarthome
  script:
    - docker build -f docker/php/DockerfileCommands -t commands-test .
    - docker compose -f docker-compose.ci.yaml build php
    - docker compose -f docker-compose.ci.yaml down --remove-orphans
    - cp -n .env.test .env.test.local
    - docker compose -f docker-compose.ci.yaml up -d

test-compose:
  stage: testing
  tags:
    - smarthome
  dependencies:
    - test-build
  script:
    - docker compose -f docker-compose.ci.yaml run -T php composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - docker compose -f docker-compose.ci.yaml run -T php php -v

tests-testing:
  stage: testing
  tags:
    - smarthome
  dependencies:
    - test-compose
  script:
    - docker compose -f docker-compose.ci.yaml run -T php php bin/console d:d:d --force --env=test
    - docker compose -f docker-compose.ci.yaml run -T php php bin/console d:d:c --env=test
    - docker compose -f docker-compose.ci.yaml run -T php php bin/console d:m:m --no-interaction --env=test
    - docker compose -f docker-compose.ci.yaml run -T php ./vendor/codeception/codeception/codecept build
    - docker compose -f docker-compose.ci.yaml run -T php ./vendor/codeception/codeception/codecept run --steps
    - docker compose -f docker-compose.ci.yaml run -T php ./vendor/codeception/codeception/codecept clean
    - docker compose -f docker-compose.ci.yaml down --remove-orphans

#psalm:
#  stage: lint
#  script:
#    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm php /var/www/vendor/bin/psalm --no-cache --output-format=phpstorm
#  when: manual

deploy_prod:
  stage: deploy
  tags:
    - smarthome
  script:
    - df -H /
    - cd /var/www/smarthome/
    - git checkout master
    - git fetch --all
    - git reset --hard HEAD
    - git status
    - git pull
    - df -H /
    - docker compose run -T php-fpm composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - docker compose run -T php-fpm php bin/console d:m:m --no-interaction
    - docker compose down --remove-orphans
    - docker compose up -d
  dependencies:
    - tests-testing
  environment:
    name: deploy
  only:
    - master
  after_script:
    - >
      if [ $CI_JOB_STATUS == 'success' ]; then
        echo 'Success'
      else
        curl -X GET "$ALERT_HOST"
        curl -s -X POST https://api.telegram.org/bot${TG_TOKEN}/sendMessage -d chat_id="${TG_CHAT_ID}" -d text="Не может стартовать прод. Commit ${$CI_COMMIT_REF_SLUG}"
      fi
