version: "3.4"
services:
  php-fpm:
    build: ./docker/php
    container_name: uberserver-symfony
    environment:
      - "PSQL_PORT=5432"
      - "PSQL_HOST=postgres"
      - "RABBITMQ_PORT=5672"
      - "RABBITMQ_HOST=docker-rabbitmq"
    volumes:
      - ./:/var/www
    networks:
      - uberserver

  nginx:
    image: nginx:latest
    container_name: uberserver-web
    restart: always
    volumes:
      - ./:/var/www
      - ./docker/nginx/config:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
    networks:
      - uberserver


networks:
  uberserver:
    driver: bridge