version: "3.4"

services:
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php/DockerfileCI
    container_name: ci-symfony
    volumes:
      - ./docker/php/php-fpm.ini:/usr/local/etc/php/php.ini
    environment:
      - "PSQL_PORT=5432"
      - "PSQL_HOST=postgres"
      - "PHP_IDE_CONFIG=serverName=Docker"
    depends_on:
      - postgres
      - redis
    networks:
      - uberserver-microservice

  postgres:
    image: postgres:11.2-alpine
    container_name: ci-postgres
    volumes:
      - ./docker/postgres/create_extension.sql:/docker-entrypoint-initdb.d/create_extension.sql
      - ./docker/postgres/initialization-db.sql:/docker-entrypoint-initdb.d/initialization-db.sql
    ports:
      - "54333:5432"
    environment:
      - "POSTGRES_DB=test"
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=root"
    networks:
      - uberserver-microservice

  redis:
    image: redis:6.0
    container_name: redis
    networks:
      - uberserver-microservice

volumes:
  notify-postgres:

networks:
  uberserver-microservice:
    driver: bridge
