version: "3.4"
services:
  php-fpm:
    image: registry.gitlab.com/decole/uberserver-symfony:app
    container_name: ci-symfony
    environment:
      - "PSQL_PORT=5432"
      - "PSQL_HOST=postgres"
      - "PHP_IDE_CONFIG=serverName=Docker"
    volumes:
      - ./:/var/www
      - ./docker/php/php-fpm.ini:/usr/local/etc/php/php.ini
    networks:
      - uberserver-microservice

  nginx:
    image: nginx:alpine
    container_name: ci-nginx
    restart: always
    volumes:
      - ./:/var/www
      - ./docker/nginx/config:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
    depends_on:
      - php-fpm
    ports:
      - "${CI_WEB_PORT}:80"
    networks:
      - uberserver-microservice

  postgres:
    image: postgres:11.2-alpine
    container_name: ci-postgres
    volumes:
      - ./docker/postgres/create_extension.sql:/docker-entrypoint-initdb.d/create_extension.sql
    ports:
      - "54333:5432"
    environment:
      - "POSTGRES_DB=test"
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=root"
    networks:
      - uberserver-microservice

  rabbitmq:
    image: rabbitmq
    container_name: ci-rabbitmq
    volumes:
      - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    environment:
      - "RABBITMQ_DEFAULT_USER=rabbit"
      - "RABBITMQ_DEFAULT_PASS=rabbit"
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - uberserver-microservice

  redis:
    image: redis:6.0
    container_name: redis
    networks:
      - uberserver

volumes:
  notify-postgres:
  notify-rabbitmq:

networks:
  uberserver-microservice:
    driver: bridge
