services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Domain\SecureSystem\Service\RegistrationValidateService: ~

  App\Domain\SecureSystem\Service\LoginFormAuthenticator: ~

  App\Domain\Page\Service\PageGidratorService: ~

  App\Domain\PeriodicHandleCriteria\:
    resource: '%kernel.project_dir%/src/Domain/PeriodicHandleCriteria/**/*Criteria.php'
    tags: [ 'periodic.criteria' ]
    autowire: true

  App\Domain\DeviceData\Service\DeviceDataResolver: ~

  App\Domain\PLC\Factory\PlcCrudFactory: ~
  App\Domain\FireSecurity\Factory\FireSecurityCrudFactory: ~
  App\Domain\Sensor\Factory\SensorCrudFactory: ~
  App\Domain\Page\Factory\PageCrudFactory: ~
  App\Domain\Relay\Factory\RelayCrudFactory: ~
  App\Domain\Security\Factory\SecurityCrudFactory: ~
  App\Domain\Profile\Factory\ProfileCrudFactory: ~

  App\Domain\:
    resource: '%kernel.project_dir%/src/Domain/**/*Service.php'
    autowire: true
