services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Domain\Doctrine\SecureSystem\Service\RegistrationValidateService: ~

  App\Domain\Doctrine\SecureSystem\Service\LoginFormAuthenticator: ~