imports:
  - { resource: 'events.yaml' }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Domain\SecureSystem\Service\RegistrationValidateService: ~
  App\Domain\SecureSystem\Service\LoginFormAuthenticator: ~

  App\Domain\Page\Service\PageHydrateService: ~

  App\Domain\DeviceData\Service\DeviceDataResolver: ~

  App\Domain\PLC\Factory\PlcCrudFactory: ~
  App\Domain\FireSecurity\Factory\FireSecurityCrudFactory: ~
  App\Domain\Sensor\Factory\SensorCrudFactory: ~
  App\Domain\Page\Factory\PageCrudFactory: ~
  App\Domain\Relay\Factory\RelayCrudFactory: ~
  App\Domain\Security\Factory\SecurityCrudFactory: ~
  App\Domain\Profile\Factory\ProfileCrudFactory: ~

  App\Domain\:
    resource: '%kernel.project_dir%/src/Domain/**/*Service.php'
    autowire: true

  App\Domain\ScheduleTask\Service\ScheduleTaskService:
    arguments:
      $logger: '@monolog.logger.schedule_service'

  App\Domain\SecureSystem\Service\RestorePasswordService:
    arguments:
      $email: '%env(EMAIL_REGISTRATION_EMAIL)%'
      $subject: '%env(EMAIL_RESTORE_SUBJECT)%'

  App\Domain\SecureSystem\Service\TwoFactorQrCodeService:
    arguments:
      $host: '%env(APP_HOST)%'