services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Domain\SecureSystem\Service\RegistrationValidateService: ~

  App\Domain\SecureSystem\Service\LoginFormAuthenticator: ~

  App\Domain\Page\Service\PageGidratorService: ~

  App\Domain\PeriodicHandleCriteria\:
    resource: '%kernel.project_dir%/src/Domain/PeriodicHandleCriteria/**/*Criteria.php'
    tags: [ 'periodic.criteria' ]
    autowire: true