services:
  _defaults:
    autowire: true
    autoconfigure: true
  _instanceof:
    App\Infrastructure\Repository\BaseDoctrineRepository:
      tags: [ 'doctrine.repository' ]
      calls:
        - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]

  Doctrine\ORM\EntityManager: '@doctrine.orm.entity_manager'

  App\Infrastructure\Repository\:
    resource: '%kernel.project_dir%/src/Infrastructure/Repository/**/*Repository.php'
    autowire: true

  # Репозиторий security обертки Symfony, под общее правило не подпадает. Регистрирую отдельно
  App\Domain\Identity\Repository\UserRepositoryInterface:
    class: App\Infrastructure\Repository\Identity\UserRepository