services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Infrastructure\Event\:
    resource: '%kernel.project_dir%/src/Infrastructure/Event/**/*Listener.php'

  App\Domain\:
    resource: '%kernel.project_dir%/src/Domain/**/*Listener.php'