App\Domain\Doctrine\Identity\Entity\Activity:
  type: embeddable
  fields:
    registeredAt:
      type: datetime_immutable
    isConfirmed:
      type: boolean
    isBlocked:
      type: boolean
    updatedAt:
      type: datetime_immutable
      nullable: true
    lastLoginAt:
      type: datetime_immutable
      nullable: true