App\Domain\Doctrine\Identity\Entity\Contact:
  type: embeddable
  fields:
    email:
      type: string
      unique: true
    telegram:
      type: string
      nullable: true
    telegramId:
      type: bigint
      nullable: true