App\Domain\Doctrine\Identity\Entity\Token:
  type: entity
  fields:
    id:
      id: true
      type: uuid
    token:
      type: string
    tokenType:
      type: string
    isDeleted:
      type: boolean
    deletedAt:
      type: datetime_immutable
      nullable: true
    createdAt:
      type: datetime_immutable
    updatedAt:
      type: datetime_immutable
      nullable: true
  manyToOne:
    user:
      targetEntity: App\Domain\Doctrine\Identity\Entity\User