App\Domain\Identity\Entity\User:
  table: '`user`'
  type: entity
  inheritanceType: JOINED
  discriminatorColumn:
    name: user_type
    type: string
  fields:
    id:
      id: true
      type: uuid
    email:
      type: string
      unique: true
      length: 180
    roles:
      type: json
    password:
      type: string
    isVerified:
      type: boolean
      name: 'is_verified'
    name:
      type: string
      unique: true
    telegramId:
      type: integer
      name: telegram_id
      nullable: true
    restoreToken:
      type: string
      name: restore_token
      nullable: true
    restoreTokenCreatedAt:
      type: datetime_immutable
      name: restore_token_created_at
      nullable: true