App\Domain\Identity\Entity\User:
  table: '`user`'
  type: entity
  inheritanceType: JOINED
  discriminatorColumn:
    name: user_type
    type: string
  fields:
    id:
      id: true
      type: uuid
    email:
      type: string
      unique: true
      length: 180
    roles:
      type: json
    password:
      type: string
    isVerified:
      type: boolean
    name:
      type: string
      unique: true
    telegramId:
      type: integer
      nullable: true