App\Domain\Doctrine\Identity\Entity\User:
  table: '`user`'
  type: entity
  inheritanceType: JOINED
  discriminatorColumn:
    name: user_type
    type: string
  discriminatorMap:
    admin: App\Domain\Doctrine\User\Entity\Admin
  fields:
    id:
      id: true
      type: uuid
    isMessagesEnabled:
      type: boolean
  embedded:
    auth:
      class: App\Domain\Doctrine\Identity\Entity\Auth
      columnPrefix: false
    contact:
      class: App\Domain\Doctrine\Identity\Entity\Contact
      columnPrefix: false
    activity:
      class: App\Domain\Doctrine\Identity\Entity\Activity
      columnPrefix: false