imports:
    - { resource: 'domain/services.yaml' }
    - { resource: 'application/services.yaml' }
    - { resource: 'infrastructure/services.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true
