imports:
    - { resource: 'domain/services.yaml' }
    - { resource: 'application/services.yaml' }
    - { resource: 'infrastructure/services.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            - '@redis_client'
            - { 'prefix': 'session_', 'ttl': 31536000 }

parameters:
    app.registration: '%env(APP_REGISTRATION_ENABLE)%'
    app.host: '%env(APP_HOST)%'