services:
  _defaults:
    public: true

  Symfony\Component\PasswordHasher\Hasher\UserPasswordHasher:
    public: true

  App\Infrastructure\Mqtt\Entity\MqttClientInterface:
    class: App\Tests\Stub\Infrastructure\StubMqttClient

  mqtt_client:
    class: App\Tests\Stub\Infrastructure\StubMqttClient

  App\Infrastructure\SecureSystem\EventListener\ResponseEventListener:
    public: true

  Symfony\Component\HttpFoundation\Session\Session:
    public: true