imports:
    - { resource: 'domain/services.yaml' }
    - { resource: 'application/services.yaml' }
    - { resource: 'infrastructure/services.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true

parameters:
    app.registration: '%env(APP_REGISTRATION_ENABLE)%'
    app.host: '%env(APP_HOST)%'