parameters:
  app.locale: 'ru'
  app.notifications.email_sender: anonymous@example.com
  app.host: '%env(APP_HOST)%'

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
#    bind:
      # this allows to define the scalar arguments once and apply them to any services
      # defined/created in this file; if some argument is used rarely, instead of defining
      # it here you can use the #[Autowire] attribute to inject it manually in the service constructor
#      array $enabledLocales: '%kernel.enabled_locales%'
#      string $defaultLocale: '%app.locale%'

  Symfony\Component\PasswordHasher\Hasher\UserPasswordHasher:
    public: true

  App\Infrastructure\Mqtt\Entity\MqttClientInterface:
    class: App\Tests\Stub\Infrastructure\StubMqttClient

  mqtt_client:
    class: App\Tests\Stub\Infrastructure\StubMqttClient

  App\Infrastructure\SecureSystem\EventListener\ResponseEventListener:
    public: true

  Symfony\Component\HttpFoundation\Session\Session:
    public: true
