App\Domain\Doctrine\Sensor\Entity\Sensor:
  type: entity
  fields:
    id:
      id: true
      type: uuid
    name:
      type: string
      unique: true
    topic:
      type: string
      unique: true
    payload_min:
      type: integer
    payload_max:
      type: integer
    payload:
      type: string
      nullable: true
    message_info:
      type: string
      nullable: true
    message_ok:
      type: string
      nullable: true
    message_warn:
      type: string
      nullable: true
    type:
      type: smallint
    status:
      type: smallint
    notify:
      type: boolean
    createdAt:
      type: datetime_immutable
      name: created_at
    updatedAt:
      type: datetime_immutable
      name: updated_at
      nullable: true