App\Domain\Doctrine\Sensor\Entity\Sensor:
  table: 'sensor'
  type: entity
  inheritanceType: JOINED
  discriminatorColumn:
    name: sensor_type
    type: string
  discriminatorMap:
    temperature: App\Domain\Doctrine\Sensor\Entity\TemperatureSensor
    humidity: App\Domain\Doctrine\Sensor\Entity\HumiditySensor
    leakage: App\Domain\Doctrine\Sensor\Entity\LeakageSensor
    pressure: App\Domain\Doctrine\Sensor\Entity\PressureSensor
    dryContact: App\Domain\Doctrine\Sensor\Entity\DryContactSensor
  fields:
    id:
      id: true
      type: uuid
    name:
      type: string
      unique: true
    topic:
      type: string
      unique: true
    payload:
      type: string
      nullable: true
    status:
      type: smallint
    notify:
      type: boolean
    createdAt:
      type: datetime_immutable
      name: created_at
    updatedAt:
      type: datetime_immutable
      name: updated_at
      nullable: true
  embedded:
    statusMessage:
      class: App\Domain\Doctrine\Common\Embedded\StatusMessage
      columnPrefix: false