App\Domain\FireSecurity\Entity\FireSecurity:
  table: 'fire_security'
  type: entity
  fields:
    id:
      id: true
      type: uuid
    name:
      type: string
      unique: true
    topic:
      type: string
      unique: true
    payload:
      type: string
      nullable: true
    normalPayload:
      name: detect_payload
      type: string
    alertPayload:
      name: hold_payload
      type: string
    lastCommand:
      type: string
      name: last_command
      nullable: true
    status:
      type: smallint
    notify:
      type: boolean
    createdAt:
      type: datetime_immutable
      name: created_at
    updatedAt:
      type: datetime_immutable
      name: updated_at
      nullable: true
  embedded:
    statusMessage:
      class: App\Domain\Common\Embedded\StatusMessage
      columnPrefix: false